
name: MINIKUBE DEPLOYMENT PIPELINE

on: 
  push:
    branches:
      - main

jobs: 
  build and push docker file to docker hub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: short sha
        run: |
             echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: build image
        run: |
             build -t amadidominic15/minikube-devops-project:${{ env.SHORT_SHA}} .
      - name: login to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: push to docker hub
        run: |
             docker push amadidominic15/minikube-devops-project:${{ env.SHORT_SHA}}

